index:
    path: /
    defaults: { _controller: 'Bookshelf\Controller\HomeController::handleAction' }

login:
  path: /login
  defaults: { _controller: 'Bookshelf\Controller\SecurityController::loginAction' }

login_check:
  path: /login_check

logout:
  path: /logout

change_password:
  path: /change_password
  defaults: { _controller: 'Bookshelf\Controller\User\ChangePasswordController::handleAction' }

# Books
books:
  path: /books
  defaults: { _controller: 'Bookshelf\Controller\Book\ListController::handleAction', page: 1 }
  methods: [GET]

books_paginated:
  path: /books/{page}
  defaults: { _controller: 'Bookshelf\Controller\Book\ListController::handleAction' }
  requirements:
    page: '[1-9]\d*'
  methods: [GET]

book_create:
  path: /books
  defaults: { _controller: 'Bookshelf\Controller\Book\CreateController::handleAction' }
  methods: [POST]

# Authors
authors:
  path: /authors
  defaults: { _controller: 'Bookshelf\Controller\Author\ListController::handleAction', page: 1 }
  methods: [GET]

authors_paginated:
  path: /authors/{page}
  defaults: { _controller: 'Bookshelf\Controller\Author\ListController::handleAction' }
  requirements:
    page: '[1-9]\d*'
  methods: [GET]

authors_json:
  path: /authors.json
  defaults: { _controller: 'Bookshelf\Controller\Author\JsonController::handleAction', page: 1 }
  methods: [GET]

author_create:
  path: /authors
  defaults: { _controller: 'Bookshelf\Controller\Author\CreateController::handleAction' }
  methods: [POST]

# Logs
read_log_create:
  path: /logs
  defaults: { _controller: 'Bookshelf\Controller\ReadLog\CreateController::handleAction' }
  methods: [GET,POST]

read_log_edit:
  path: /logs/{id}
  defaults: { _controller: 'Bookshelf\Controller\ReadLog\EditController::handleAction' }
  methods: [GET,POST]
  requirements:
    id: '[1-9]\d*'

read_log_search:
  path: /logs/search
  defaults: { _controller: 'Bookshelf\Controller\ReadLog\SearchController::handleAction' }
  methods: [GET]
