index:
    path: /
    defaults: { _controller: 'Bookshelf\Controller\HomeController::indexAction' }

login:
  path: /login
  defaults: { _controller: 'Bookshelf\Controller\SecurityController::loginAction' }

login_check:
    path: /login_check

logout:
    path: /logout